name: Makefile CI

on:
  push:
    branches: [ "main", "ci-testing" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: create homebrew directory
      run: mkdir -p /opt/homebrew/opt/

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v2
      with:
        version: "10.0"
        directory: /opt/homebrew/opt/llvm

    - name: Place header files in expected directory
      run: |
        mkdir -p /opt/homebrew/Cellar/llvm/18.1.6/lib/clang/18/include
        cp /opt/homebrew/opt/llvm/lib/clang/10.0.1/include/stdarg.h /opt/homebrew/Cellar/llvm/18.1.6/lib/clang/18/include/
        cp /opt/homebrew/opt/llvm/lib/clang/10.0.1/include/stdint.h /opt/homebrew/Cellar/llvm/18.1.6/lib/clang/18/include/
            

    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make

    - uses: actions/upload-artifact@v4
      with:
        name: kernel8.img
        path: ./kernel8.img
