name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make

    - uses: actions/upload-artifact@v4
      with:
        name: kernel8.img
        path: ./kernel8.img
